name: Treecapitator
main: io.github.jacksonchen666.treecapitator.Main
author: JacksonChen666
api-version: "1.16" # https://www.spigotmc.org/wiki/plugin-yml/
version: 1.0.0
description: Capitates trees just like Hypixel

commands:
  treecapitator:
    description: Get a Treecapitator!