name: TreeCap
main: io.github.jacksonchen666.treecap.Main
author: JacksonChen666
api-version: 1.16 # It should be valid because it says it here: https://www.spigotmc.org/wiki/plugin-yml/
version: 1.0-SNAPSHOT
description: Capitates trees just like Hypixel

commands:
  template:
    description: A template command

permissions:
  Template:
    default: not op
    children:
      Template.Template: true
  Template.Template:
    default: not op

# https://bukkit.gamepedia.com/Plugin_YAML