name: Build and test

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get cached gradle files
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: treecapitator-plugin
          path: build/libs/*
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Get cached gradle files
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
        continue-on-error: true
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: gradle-test-results
          path: build/reports/**
